config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "boards#index"

  resources :boards do
    resources :tasks do 
    end
  end

  resources :tasks do
    resources :comments, only:[:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :eyecatch
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy

  def has_written?(board)
    boards.exists?(id: board.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
  end

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to board_path(@board), notice: '保存できたよ'
    else
      render :new
    end
  end
    def edit
      @board = current_user.boards.find(params[:id])
    end

    def update
      @board = current_user.boards.find(params[:id])
      if @board.update(board_params)
        redirect_to board_path(@board)
      else
        render :edit
      end
    end

    def destroy
      board = current_user.boards.find(params[:id])
      board.destroy!
      redirect_to root_path
    end

  private
  def board_params
    params.require(:board).permit(:title, :content)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @task = Task.find(params[:task_id])
    @comment = @task.comments.build
  end

  def create
    @task = Task.find(params[:task_id])
    @comments = @task.comments.build(comment_params)
    if @comments.save!
      redirect_to board_task_path(board_id: @task.board_id, id: @task.id)
    else
      render :new
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    board = Board.find(params[:board_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:board_id])
    @task = board.tasks.build(task_params)
    if @task.save!
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def show
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])
    @comments = @task.comments
     # =>  /boards/:board_id/tasks/:id(:format)
     # => idが2つ使えるようになる
  end

  def edit
    @task = Task.find(params[:id])
    @board = Board.find(params[:board_id])
  end

  def update
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])


    if @task.update(task_params)
      redirect_to board_task_path(@board.id, @task.id)
    else
      render new
    end
  end

  def destroy
    @board = Board.find(params[:board_id])
    @task = @board.tasks.find(params[:id])

    @task.destroy!
    redirect_to board_path(@board)

  end


  private
  def task_params
    params.require(:task).permit(:title, :content, :eyecatch).merge(user_id: current_user.id )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/edit.html.erb
<div class="container">
  <div class="card-title">
    <h2>New board</h2>
  </div>
    <ul>
  <% @board.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
    </ul>
  <%= form_with(model: @board, url: board_path(@board), method: 'put', local: true) do |f| %>
    <div  class = 'text-around' >
      <%= f.label :title, 'Name', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_field :title , class: 'text'%>
    </div>
    <div class = 'text-around' >
      <%= f.label :content, 'Description', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_area :content, class: 'text-content'%>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>

  <% end %>
</div>

app/views/boards/index.html.erb
<div class="container">
  <h1>All Board</h1>
  <% @boards.each do |board| %>
    <div class="card">
      <div class="card-title">
        <%= link_to board_path(id: board.id) do %>
          <p class = 'card-title-left'><%= board.title %></p>
        <% end %>
        <%= image_tag 'Combined Shape.png', :class => 'card-title-right dropbtn' %>
      </div>
        <div class="content">
          <p class = "card-content"><%= board.content %></p>
          <% if user_signed_in? && current_user.id == board.user_id %>
            <div class="content-drop drop-btn">
              <%= link_to 'Edit', edit_board_path(id: board.id), class: 'edit-text' %>
              <%= link_to 'Delete', board_path(board), data: { method: 'delete', confirm: '本当に削除しますか？' }, class: 'delete-text' %>
            </div>
          <% end %>
        </div>
      <%= image_tag 'Oval (1).png', :class => 'card-avatar' %>
    </div>
  <% end %>
  <%= link_to new_board_path do %>
    <div class="new-card">
      <p class="new-board">+ Add new board</p>
    </div>
  <% end %>
</div>

app/views/boards/new.html.erb
<div class="container">
  <div class="card-title">
    <h2>New board</h2>
  </div>
    <ul>
  <% @board.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
    </ul>
  <%= form_with(model: @board, url: boards_path, method: 'post', local: true) do |f| %>
    <div  class = 'text-around' >
      <%= f.label :title, 'Name', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_field :title , class: 'text'%>
    </div>
    <div class = 'text-around' >
      <%= f.label :content, 'Description', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_area :content, class: 'text-content'%>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>

  <% end %>
</div>

app/views/boards/show.html.erb
<div class="container">
  <h2>Brackets</h2>
  <% @tasks.each do |task| %> 
    <div class="card">
      <% if task.eyecatch.attached? %>
        <div class = "card-image-around">
          <%= image_tag task.eyecatch, :class => 'card-image' %>
        </div>
      <% end %>
      <div class="card-title">
          <%= link_to board_task_path(@board.id, id: task[:id]), class: 'task-show' do %>
            <h2 class = 'task-show-title'><%= task.title %></h2>
          <% end %>
      </div>
        <div class="content">
          <p class = "card-content"><%= task.content %></p>
        </div>
      <%= image_tag 'Oval (1).png', :class => 'card-avatar' %>
    </div>
  <% end %>

  <%= link_to new_board_task_path(@board) do %>
    <div class="new-card">
      <p class="new-board">+ Add new card</p>
    </div>
  <% end %>
</div>

app/views/comments/new.html.erb
<div class="container">
  <div class = "card-title">
    <h2>New Comment</h2>
  </div>
  <%= form_with(model: @comment, url: task_comments_path(@task), local: true) do |f| %>
    <div class = 'text-around' >
      <div>
        <%= f.text_area :content, class: 'text-content'%>
      </div>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boardapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header class="header">
      <div class="container">
        <div class = header-title>
          <%= link_to 'Board', root_path, class: "header-right" %>
          <% if user_signed_in? %>
            <%= image_tag 'Oval.png', :class => 'header-avatar-left dropbtn'%>
            <div class="dropdown-content">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
          <% else %>
              <%= link_to 'ログイン', new_user_session_path, :class => 'loginpage'%>
            </div>
          <% end %>
      </div>
      <div class="line"></div>
    </header>
    <p class="notice fadeOut"><%= notice %></p>
    <p class="alert fadeOut"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="card-title">
    <h2>New Card</h2>
  </div>
  <%= form_with(model: @task, url: board_task_path(@task.board), method: 'put', local: true) do |f| %>
    <div class = 'text-around'>
      <%= f.label :eyecatch, 'アイキャッチ' %>
    </div>
    <div class = 'text-around'>
      <%= f.file_field :eyecatch %>
    </div>
    <div  class = 'text-around' >
      <%= f.label :title, 'Name', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_field :title , class: 'text'%>
    </div>
    <div class = 'text-around' >
      <%= f.label :content, 'Description', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_area :content, class: 'text-content'%>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>

<% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="card-title">
    <h2>New board</h2>
  </div>
  <%= form_with(model: @task, url: board_tasks_path(@task.board), method: 'post', local: true) do |f| %>
    <div class = 'text-around'>
      <%= f.label :eyecatch, 'アイキャッチ' %>
    </div>
    <div class = 'text-around'>
      <%= f.file_field :eyecatch %>
    </div>
    <div  class = 'text-around' >
      <%= f.label :title, 'Name', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_field :title , class: 'text'%>
    </div>
    <div class = 'text-around' >
      <%= f.label :content, 'Description', class: 'text-title'%>
    </div>
    <div>
      <%= f.text_area :content, class: 'text-content'%>
    </div>

    <%= f.submit 'Submit', class: 'btn-primary' %>

<% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="task-title">
    <h2 class="task-title-left"><%= @task.title %></h2>
    <div class="task-title-right">
      <%= link_to 'Edit', edit_board_task_path(@board, @task), class: 'task-text' %>
      <%= link_to 'Delete', board_task_path(@board, @task), data: { method: 'delete', confirm: '本当に削除しますか？' }, class: 'task-text' %>
    </div>
  </div>
  <% if @task.eyecatch.attached? %>
    <div class="task-image">
      <%= image_tag @task.eyecatch, class: 'image' %>
    </div>
  <% end %>
  <div class="task-content">
    <div class="task-content-text"><%= @task.content %></div>
  </div>

  <div class="comment">
    <p class = "comment-title">Comment</p>
    <% @comments.each do |comment| %>
      <div class = comment-content>
        <p><%= comment.content %></p>
      </div>
    <% end %>
  </div>

  <div class = "comment">
    <%= link_to new_task_comment_path(@board, @task) do %>
    <p class="add-comment">Add new comment</p>
    <% end %>
</div>